/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubmissionsIndexRouteImport } from './routes/submissions/index'
import { Route as ProblemsIndexRouteImport } from './routes/problems/index'
import { Route as SubmissionsSubmissionIdRouteImport } from './routes/submissions/$submissionId'
import { Route as ProblemsProblemIdRouteImport } from './routes/problems/$problemId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsIndexRoute = SubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsIndexRoute = ProblemsIndexRouteImport.update({
  id: '/problems/',
  path: '/problems/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsSubmissionIdRoute = SubmissionsSubmissionIdRouteImport.update({
  id: '/submissions/$submissionId',
  path: '/submissions/$submissionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsProblemIdRoute = ProblemsProblemIdRouteImport.update({
  id: '/problems/$problemId',
  path: '/problems/$problemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRoute
  '/problems': typeof ProblemsIndexRoute
  '/submissions': typeof SubmissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRoute
  '/problems': typeof ProblemsIndexRoute
  '/submissions': typeof SubmissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRoute
  '/problems/': typeof ProblemsIndexRoute
  '/submissions/': typeof SubmissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/problems/$problemId'
    | '/submissions/$submissionId'
    | '/problems'
    | '/submissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/problems/$problemId'
    | '/submissions/$submissionId'
    | '/problems'
    | '/submissions'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/problems/$problemId'
    | '/submissions/$submissionId'
    | '/problems/'
    | '/submissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProblemsProblemIdRoute: typeof ProblemsProblemIdRoute
  SubmissionsSubmissionIdRoute: typeof SubmissionsSubmissionIdRoute
  ProblemsIndexRoute: typeof ProblemsIndexRoute
  SubmissionsIndexRoute: typeof SubmissionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/': {
      id: '/submissions/'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/': {
      id: '/problems/'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/$submissionId': {
      id: '/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/submissions/$submissionId'
      preLoaderRoute: typeof SubmissionsSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/$problemId': {
      id: '/problems/$problemId'
      path: '/problems/$problemId'
      fullPath: '/problems/$problemId'
      preLoaderRoute: typeof ProblemsProblemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProblemsProblemIdRoute: ProblemsProblemIdRoute,
  SubmissionsSubmissionIdRoute: SubmissionsSubmissionIdRoute,
  ProblemsIndexRoute: ProblemsIndexRoute,
  SubmissionsIndexRoute: SubmissionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
